#####################
# Ubuntu
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and disk_additional_disks

#####################
# Debian
- include: debian.yml
  when: ansible_distribution == 'Debian' and disk_additional_disks

- include: parted.yml
# XXX: lvm is not implemented for now.
# - include: lvm.yml
- include: format.yml
- include: mount.yml
