- name: "Ensure that group {{ disk_group }} exist"
  group: name={{ disk_group }}
  when: disk_group is defined
  tags:
    - disk

- name: "Ensure that user {{ disk_user }} exist"
  user: >
      name={{ disk_user }} 
      group={{ disk_group }} 
      shell=/bin/bash
  when: disk_group is defined and disk_user is defined
  tags:
    - disk

- name: "Ensure the /data directory exists"
  file: >
    path={{ item.mount }}
    owner={{ disk_user | default('root') }}
    group={{ disk_group | default('root') }}
    state=directory
  with_items: disk_additional_disks
  tags:
    - disk

- name: "Mount additional disk"
  mount: >
    name={{ item.mount }}
    fstype={{ item.fstype }}
    opts={{ item.mount_options }}
    passno=0
    src={{ item.disk }}1
    state=mounted
  with_items: disk_additional_disks
  tags:
    - disk
