- name: update cache
  apt: >
      update_cache=yes 
      cache_valid_time=3600
  environment: proxy_env
  tags:
    - disk
    - pkgs

- name: "Install packages"
  apt: >
    name={{ item }}
    state=present
  environment: proxy_env
  with_items: 
    - util-linux
    - parted
    - lvm2
  tags:
    - disk
    - pkgs
