# Run it as:
#   `ansible-playbook create-server.yml -vvv -e "storage_password=XXX"`
#

# Uncomment to create disk
- name: Create and mount disk
  hosts: storage_servers
  sudo: yes
  vars:
    proxy_env: {}
  roles:
    - ansible-disk
  tags:
    - disk-only


- name: Create SAMBA server
  hosts: storage_servers
  vars:
    deploy_user: "{{ ansible_ssh_user }}"
    # turn off/on debug deploy
    deploy_debug: yes
    # other vars
    proxy_env: {}
    site_name: plaque-data
    storage_password: Q0LGZjBRWcgYX
  roles:
    - samba-server
