- name: update cache
  apt: >
      update_cache=yes 
      cache_valid_time=3600
  environment: proxy_env
  tags:
    - disk
    - pkgs

- name: "Install samba"
  environment: proxy_env
  apt: >
    name={{ item }}
    state=present
  with_items:
    # - cups-libs
    - samba
    - samba-common
    - samba-client
  tags:
    - disk
    - pkgs
